name: Retrieve and Validate Build Ids

on:
  workflow_call:
    inputs:
      component:
        description: Application Component
        required: true
        type: string
      component_build_ids:
        description: 'Component Build Ids: (i.e gp2gp=PR-855-10-50e5138,gpcc=PR-811-1-20e3452)'
        required: false
        type: string
    outputs:
      validated_build_ids:
        description: The validated build ids as JSON
        value: ${{ jobs.validate-build-ids.outputs.validated_build_ids }}

jobs:
  validate-build-ids:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      validated_build_ids: ${{ steps.validate.outputs.validated_build_ids }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_TO_ASSUME }}"
          role-session-name: github_manual_terraform_job
          aws-region: ${{ secrets.AWS_REGION }}

      - name: 'Checkout Terraform Repository'
        uses: actions/checkout@v4.1.7

      - name: Set empty validated_build_ids for 'account' component
        if: ${{ inputs.component == 'account' }}
        id: set-empty-for-account
        run: echo "validated_build_ids={}" >> $GITHUB_OUTPUT

      - name: Retrieve and Validate component build ids
        if: ${{ inputs.component != 'account' }}
        id: validate
        run: |
          $pwd
          cd ./.github/scripts
          chmod +x ./.github/scripts/validate-build-ids.sh
          ./validate-build-ids.sh
          
